name = "isup"
version = "0.1.0"

licences = ["Apache-2.0"]
description = "A simple web application to check if a given website is up or not."
repository = { type = "github", user = "J3RN", repo = "isup.website" }
links = [{ title = "Website", href = "https://isup.website" }]

[dependencies]
gleam_stdlib = "~> 0.19"
gleam_erlang = "~> 1.3"
gleam_hackney = "~> 1.0"
gleam_otp = "~> 1.2"
wisp = "~> 2.1"
gleam_http = "~> 4.3"
mist = "~> 5.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
